mutation InsertEvent($name: String, $dates: [datetime_range!], $shouldUseWeekdays: Boolean) {
  insert_events(objects: {name: $name, dates: $dates, shouldUseWeekdays: $shouldUseWeekdays}) {
    affected_rows
    returning {
      name
      id
    }
  }
}
